#!/usr/bin/python

import i3ipc
import subprocess

i3 = i3ipc.Connection()

# Current number
focused = i3.get_tree().find_focused().workspace().name
name = focused.split(': ')

# Execute rofi and store its output
rofi = ['rofi', '-dmenu', '-p', '{0}: '.format(name[0]), '-filter', name[1]]
proc = subprocess.run(rofi, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE)

# Turn output into string and strip newline
choice = proc.stdout[0:-1].decode("utf-8")

if len(choice) and choice != name[1]:
    i3.command('rename workspace to "{0}"'.format(name[0] + ": " + choice))
